### ISSUE TITLE
error in storyboard

### ISSUE THREAD

**Issue by NaturalMe** [LvJianfeng/LLCycleScrollView#8]
My LLCycleScrollView install with Cocoapods. In storyboard,  Xcode have a error:

file:///Users/zhangrunliang/Work/TestLLCycleScrollView/TestLLCycleScrollView/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ViewController (BYZ-38-t0r): dlopen(LLCycleScrollView.framework, 1): Library not loaded: @rpath/Kingfisher.framework/Kingfisher
  Referenced from: LLCycleScrollView.framework
  Reason: image not found

file:///Users/zhangrunliang/Work/TestLLCycleScrollView/TestLLCycleScrollView/Base.lproj/Main.storyboard: error: IB Designables: Failed to update auto layout status: dlopen(LLCycleScrollView.framework, 1): Library not loaded: @rpath/Kingfisher.framework/Kingfisher
  Referenced from: LLCycleScrollView.framework
  Reason: image not found

Can you help me? Thank you very much.

**Comment by LvJianfeng** [comment]
Hello, I think this is xcode bug.
Because in xcode 8.2 when I have this problem, but in xcode 8.3.2 is fixed.
If this can not solve your problem, you can cocoapods to the latest version, and than restart your xcode, try it more.

**Comment by NaturalMe** [comment]
@LvJianfeng My Xcode is 8.3.2. I upgrade my pod version to 1.2.1 and fixed. Thank you very much! Hope LLCycleScrollView good!

**Comment by brandy2015** [comment]
Hi,

Issues still remained.My Xcode is 8.3.3

file:///xcode/%E6%88%91%E5%9C%A8%E9%87%8D%E5%86%99/xxxx/Main.storyboard: error: IB Designables: Failed to update auto layout status: dlopen(LLCycleScrollView.framework, 1): Library not loaded: @rpath/Kingfisher.framework/Kingfisher
  Referenced from: LLCycleScrollView.framework
  Reason: image not found

I pod update the podfile. Then restart my Xcode. Problem still lay there.
